{
  "id": "CVE-2025-46148",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-09-25T15:16:12.007",
  "lastModified": "2025-09-25T15:16:12.007",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "In PyTorch through 2.6.0, when eager is used, nn.PairwiseDistance(p=2) produces incorrect results."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://gist.github.com/shaoyuyoung/65a587a579dfdff887b9b35bb79b9093",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/pytorch/pytorch/issues/151198",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/pytorch/pytorch/pull/152993",
      "source": "cve@mitre.org"
    }
  ]
}