{
  "id": "CVE-2025-28197",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-04-18T20:15:16.450",
  "lastModified": "2025-04-22T14:15:25.370",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "Crawl4AI \u003c=0.4.247 is vulnerable to SSRF in /crawl4ai/async_dispatcher.py."
    },
    {
      "lang": "es",
      "value": "Crawl4AI \u0026lt;=0.4.247 es vulnerable a SSRF en /crawl4ai/async_dispatcher.py."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "HIGH",
          "integrityImpact": "HIGH",
          "availabilityImpact": "NONE",
          "baseScore": 9.1,
          "baseSeverity": "CRITICAL"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 5.2
      }
    ]
  },
  "weaknesses": [
    {
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-918"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://gist.github.com/AndrewDzzz/f49e79b09ce0643ee1fc2a829e8875e0",
      "source": "cve@mitre.org"
    }
  ]
}