{
  "id": "CVE-2025-54645",
  "sourceIdentifier": "psirt@huawei.com",
  "published": "2025-08-06T04:16:16.270",
  "lastModified": "2025-08-06T04:16:16.270",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "Out-of-bounds array access issue due to insufficient data verification in the location service module.\nImpact: Successful exploitation of this vulnerability may affect availability."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "psirt@huawei.com",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
          "attackVector": "LOCAL",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "REQUIRED",
          "scope": "CHANGED",
          "confidentialityImpact": "LOW",
          "integrityImpact": "LOW",
          "availabilityImpact": "NONE",
          "baseScore": 5,
          "baseSeverity": "MEDIUM"
        },
        "exploitabilityScore": 1.8,
        "impactScore": 2.7
      }
    ]
  },
  "weaknesses": [
    {
      "source": "psirt@huawei.com",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-129"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://consumer.huawei.com/en/support/bulletin/2025/8/",
      "source": "psirt@huawei.com"
    }
  ]
}