{
  "id": "CVE-2025-29631",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-07-25T17:15:31.510",
  "lastModified": "2025-07-25T17:15:31.510",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue in Gardyn 4 allows a remote attacker execute arbitrary code"
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "http://gardyn.com",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/mselbrede/gardyn/blob/main/CVE-2025-29628_CVE-2025-29631.md",
      "source": "cve@mitre.org"
    }
  ]
}