{
  "id": "CVE-2025-2853",
  "sourceIdentifier": "cve@gitlab.com",
  "published": "2025-05-22T14:16:02.677",
  "lastModified": "2025-05-23T15:55:02.040",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue has been discovered in GitLab CE/EE affecting all versions before 17.10.7, 17.11 before 17.11.3, and 18.0 before 18.0.1. A lack of proper validation in GitLab could allow an authenticated user to cause a denial of service condition."
    },
    {
      "lang": "es",
      "value": "Se ha detectado un problema en GitLab CE/EE que afecta a todas las versiones anteriores a la 17.10.7, 17.11 anteriores a la 17.11.3 y 18.0 anteriores a la 18.0.1. La falta de una validación adecuada en GitLab podría permitir que un usuario autenticado provoque una denegación de servicio."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "cve@gitlab.com",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "LOW",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "availabilityImpact": "HIGH",
          "baseScore": 6.5,
          "baseSeverity": "MEDIUM"
        },
        "exploitabilityScore": 2.8,
        "impactScore": 3.6
      }
    ]
  },
  "weaknesses": [
    {
      "source": "cve@gitlab.com",
      "type": "Primary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-770"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/527218",
      "source": "cve@gitlab.com"
    },
    {
      "url": "https://hackerone.com/reports/3015673",
      "source": "cve@gitlab.com"
    }
  ]
}