{
  "id": "CVE-2025-46152",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-09-25T15:16:12.470",
  "lastModified": "2025-09-25T15:16:12.470",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "In PyTorch before 2.7.0, bitwise_right_shift produces incorrect output for certain out-of-bounds values of the \"other\" argument."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/pytorch/pytorch/issues/143555",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/pytorch/pytorch/pull/143635",
      "source": "cve@mitre.org"
    }
  ]
}