{
  "id": "CVE-2025-3831",
  "sourceIdentifier": "cve@checkpoint.com",
  "published": "2025-08-12T15:15:29.573",
  "lastModified": "2025-08-13T17:34:12.350",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "Log files uploaded during troubleshooting by the Harmony SASE agent may have been accessible to unauthorized parties."
    },
    {
      "lang": "es",
      "value": "Es posible que terceros no autorizados hayan podido acceder a los archivos de registro cargados durante la resoluci√≥n de problemas por parte del agente Harmony SASE."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "cve@checkpoint.com",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "attackVector": "NETWORK",
          "attackComplexity": "HIGH",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "HIGH",
          "integrityImpact": "HIGH",
          "availabilityImpact": "HIGH",
          "baseScore": 8.1,
          "baseSeverity": "HIGH"
        },
        "exploitabilityScore": 2.2,
        "impactScore": 5.9
      }
    ]
  },
  "weaknesses": [
    {
      "source": "cve@checkpoint.com",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-200"
        },
        {
          "lang": "en",
          "value": "CWE-798"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://support.checkpoint.com/results/sk/sk183761",
      "source": "cve@checkpoint.com"
    }
  ]
}